n1=float(input("digite seu numero: "))
n2=float(input("digite seu numero: "))
n3=float(input("digite seu numero: "))
max= max(n1,n2,n3)
min= min(n1,n2,n3)
meio= (n1+n2+n3)-(max+min)
print(f"{min}")
print(f"{meio}")
print(f"{max}")